### ISSUE TITLE
gen 2-7

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/pk2pk#4]
Hey you can do this whenever they come out with gen 2 conversion officially just in case you need to chnage this but I just wanted to remind you about gen 2-7 for pk2pk. Thanks

**Comment by kwsch** [comment]
just swap the dll with the latest from PKHeX

will probably update it closer to the US/UM release.

**Comment by kwsch** [comment]
Closed via https://github.com/kwsch/pk2pk/commit/af28b58167df7e5265a2f9c3b8a543c5f6826e73
