### ISSUE TITLE
not able to convert pokemon

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/pk2pk#5]
For some reason I am not able to convert any pokemon. When I drag a pokemon onto the program, it doesn't do anything. I tried multiple generations and sometimes I get this error.

constructor on type 'PKHeX.Core.PK7' not found

this happens for all gens so the above message was just from when I was converting to a pk7

**Comment by kwsch** [comment]
Did you change the PKHeX.Core.dll?

**Comment by NinFanBoyFTW** [comment]
no. I used the one from the current pk2pk github build
